### ISSUE TITLE
Stage 3 - Review requirements checklist

### ISSUE THREAD

**Issue by JeremieLitzler** [JeremieLitzler/mws.nd.2018.s3#1]
### User Interface

- [x] Users are able to mark a restaurant as a favorite, this toggle is visible in the application. A form is added to allow users to add their own reviews for a restaurant. Form submission works properly and adds a new review to the database.
  - [x] A restaurant can be marked as favorite
    - [ ] [BONUS] On index page
    - [x] On restaurant details
  - [x] More than one restaurant can be marked as favorite
  - [x] The state of the favorites is maintained on the client-side
  - [x] The state of the favorites is saved to the API
  - [x] The form works
    - [x] A message is displayed to the user when the review is saved
    - [x] The added review appears in the list of reviews.

### Offline Use

- [x] The client application works offline. 
- [x] JSON responses are cached using the IndexedDB API. 
- [x] Any data previously accessed while connected is reachable while offline. 
- [x] User is able to add a review to a restaurant while offline and the review is sent to the server when connectivity is re-established.
  - [ ] [BONUS] A notification is shown to the user when the sync is done.

### Responsive Design

- [x] The application maintains a responsive design on mobile, tablet and desktop viewports. All new features are responsive, including the form to add a review and the control for marking a restaurant as a favorite.

### Accessibility

- [x] The application retains accessibility features from the previous projecs. Images have alternate text, the application uses appropriate focus management for navigation, and semantic elements and ARIA attributes are used correctly. Roles are correctly defined for all elements of the review form.
  - [x] The form can navigated through using keyboard only
  - [x] The inputs can selected / filled using keyboard only

### Site Performance

- [x] Lighthouse targets for each category exceed:
  - [x] Progressive Web App: >90
  - [x] Performance: >90
  - [x] Accessibility: >90
